import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import RobotoPage from '@/components/RobotoPage'

// const inter = Inter({ subsets: ['Lato'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Robotics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <RobotoPage></RobotoPage>
 
    </>
  )
}
